# Generated by Django 5.2.17 on 2026-10-02 19:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0018_storylines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('alerts', models.BooleanField(default=True)),
                ('depth', models.BooleanField(default=True)),
                ('exports', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new', 'New event'), ('update', 'Update')], max_length=8)),
                ('tier', models.PositiveSmallIntegerField()),
                ('evidence_level', models.CharField(max_length=16)),
                ('breaking', models.BooleanField(default=False)),
                ('held', models.CharField(blank=True, choices=[('', 'Pushed'), ('quiet', 'Quiet hours'), ('cap', 'Daily push cap')], default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.newsevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField()),
                ('evidence_level', models.CharField(max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.newsevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fcm', 'Firebase Cloud Messaging'), ('pushe', 'Pushe'), ('najva', 'Najva'), ('webpush', 'Web push')], max_length=8)),
                ('token', models.TextField()),
                ('last_seen', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=8)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('disabled', 'Channel not configured'), ('failed', 'Failed'), ('expired', 'Token expired')], max_length=8)),
                ('error', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='accounts.alert')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.device')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dial', models.CharField(choices=[('low', 'Low (tier 2+)'), ('medium', 'Medium (tier 3+)'), ('high', 'High (tier 4+)')], default='medium', max_length=8)),
                ('quiet_start', models.TimeField(default=datetime.time(23, 0))),
                ('quiet_end', models.TimeField(default=datetime.time(7, 0))),
                ('email_digest', models.BooleanField(default=False)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.watchitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', '-created_at'], name='accounts_al_user_id_1f07d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertstate',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='one_alert_state_per_event'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('kind', 'token'), name='one_device_per_token'),
        ),
        migrations.AddConstraint(
            model_name='watch',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='one_watch_per_item'),
        ),
    ]
