# Generated by Django 5.1.5 on 2026-09-02 11:16

import django.db.models.deletion
import django.utils.timezone
import inference.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(default='gapgpt', max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('memory_strategy', models.CharField(choices=[('none', 'No memory (control arm)'), ('trigram', 'Nearest approved labels by title trigram similarity'), ('semantic', 'Nearest approved labels by embedding similarity'), ('semantic+market', 'Semantic neighbours plus recent market context')], default='none', max_length=32)),
                ('memory_k', models.PositiveSmallIntegerField(default=3)),
                ('prompt_version', models.CharField(editable=False, max_length=16)),
                ('is_active', models.BooleanField(default=False, help_text='Active variants run on every cycle.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(default=inference.models.new_run_id, editable=False, max_length=32, unique=True)),
                ('mode', models.CharField(default='pipeline', max_length=32)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('aborted', 'Aborted (budget or fatal)')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('articles_fetched', models.PositiveIntegerField(default=0)),
                ('articles_processed', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=32)),
                ('error_class', models.CharField(max_length=32)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('last_error', models.TextField(blank=True)),
                ('quarantined_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_letters', to='articles.article')),
            ],
            options={
                'indexes': [models.Index(fields=['resolved_at', 'node'], name='inference_d_resolve_ea38dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'node'), name='unique_dead_letter')],
            },
        ),
        migrations.CreateModel(
            name='NodeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('success', 'Success'), ('retry', 'Retrying'), ('exhausted', 'Retries exhausted'), ('permanent', 'Permanent failure'), ('fatal', 'Fatal'), ('skipped', 'Skipped (already answered)')], max_length=16)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('error_class', models.CharField(blank=True, max_length=32)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_events', to='articles.article')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='inference.promptvariant')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inference.run')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['run', 'created_at'], name='inference_n_run_id_93b344_idx'), models.Index(fields=['node', 'status'], name='inference_n_node_abe4e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_version', models.CharField(max_length=16)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confidence_occurrence', models.CharField(blank=True, choices=[('خیلی کم', 'Very low (خیلی کم)'), ('کم', 'Low (کم)'), ('متوسط', 'Medium (متوسط)'), ('زیاد', 'High (زیاد)'), ('خیلی زیاد', 'Very high (خیلی زیاد)')], max_length=16, null=True)),
                ('gold_price_impact', models.CharField(blank=True, choices=[('خیلی کم', 'Very low (خیلی کم)'), ('کم', 'Low (کم)'), ('متوسط', 'Medium (متوسط)'), ('زیاد', 'High (زیاد)'), ('خیلی زیاد', 'Very high (خیلی زیاد)')], max_length=16, null=True)),
                ('security_relevance', models.CharField(blank=True, choices=[('خیلی کم', 'Very low (خیلی کم)'), ('کم', 'Low (کم)'), ('متوسط', 'Medium (متوسط)'), ('زیاد', 'High (زیاد)'), ('خیلی زیاد', 'Very high (خیلی زیاد)')], max_length=16, null=True)),
                ('gold_trend', models.CharField(blank=True, choices=[('↑', '↑ Up'), ('↓', '↓ Down'), ('خنثی', 'Neutral (خنثی)'), ('نامطمئن', 'Uncertain (نامطمئن)')], max_length=16, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='articles.article')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='inference.promptvariant')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='inference.run')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['article', '-created_at'], name='inference_e_article_6e9d82_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('confidence_occurrence__isnull', False), ('gold_price_impact__isnull', False)), models.Q(('confidence_occurrence__isnull', False), ('security_relevance__isnull', False)), models.Q(('gold_price_impact__isnull', False), ('security_relevance__isnull', False)), _connector='OR'), name='evaluation_assesses_at_least_two_axes')],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_version', models.CharField(max_length=16)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(choices=[('security', 'Security'), ('economics', 'Economics'), ('security/economics', 'Security/Economics'), ('other', 'Other')], max_length=32)),
                ('confidence', models.CharField(blank=True, choices=[('خیلی کم', 'Very low (خیلی کم)'), ('کم', 'Low (کم)'), ('متوسط', 'Medium (متوسط)'), ('زیاد', 'High (زیاد)'), ('خیلی زیاد', 'Very high (خیلی زیاد)')], max_length=16)),
                ('matched_keywords', models.JSONField(blank=True, default=list)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='articles.article')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='inference.promptvariant')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='inference.run')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['article', '-created_at'], name='inference_c_article_2d52ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_version', models.CharField(max_length=16)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('optimized_title', models.TextField(blank=True)),
                ('one_line', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='articles.article')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='inference.run')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='inference.promptvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['article', '-created_at'], name='inference_s_article_8fe92b_idx')],
            },
        ),
    ]
