# Generated by Django 5.1.5 on 2026-09-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='articles.article'),
        ),
    ]
