# Generated by Django 5.2.17 on 2026-09-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0003_providercircuit_and_richer_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptvariant',
            name='advanced_model',
            field=models.CharField(blank=True, help_text='Advanced model for evaluation & summarization. If blank, uses model.', max_length=64),
        ),
        migrations.AddField(
            model_name='promptvariant',
            name='classify_model',
            field=models.CharField(blank=True, help_text='Cheap model for category classification. If blank, uses model.', max_length=64),
        ),
    ]
