# Generated by Django 5.2.17 on 2026-09-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_newsevent_channels_en_newsevent_channels_fa_and_more'),
        ('inference', '0004_promptvariant_advanced_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(db_index=True, max_length=16)),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=100)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=8, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='articles.newsevent')),
            ],
        ),
    ]
