# Generated by Django 5.2.17 on 2026-10-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0005_aiusagerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('backend', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=100)),
                ('question_hash', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=3)),
                ('labelled', models.PositiveIntegerField(default=0)),
                ('grouping_pairs', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('metrics', models.JSONField(default=dict)),
                ('verdict', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('insufficient_labels', 'Insufficient labels'), ('aborted', 'Aborted')], max_length=20)),
                ('reasons', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
