# Generated by Django 5.1.5 on 2026-09-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('name', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('strategy', models.CharField(choices=[('rss_saba', 'Saba/Nastooh CMS RSS (Mehr, IRNA, ISNA)'), ('listing_detail', 'Listing page -> detail page'), ('listing_relay', 'Listing page -> interstitial -> real article')], max_length=32)),
                ('url', models.URLField(max_length=500)),
                ('archive_url', models.URLField(blank=True, max_length=500)),
                ('tier', models.PositiveSmallIntegerField(default=2)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('enabled', models.BooleanField(default=True)),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded')], default='unknown', max_length=16)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
