# Generated by Django 5.1.5 on 2026-09-02 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefilterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_category', models.SlugField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('enabled', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, help_text='Why this desk is not worth a paid call.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, help_text='Leave empty only for a slug you have verified means the same thing everywhere.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prefilter_rules', to='sources.source')),
            ],
            options={
                'ordering': ['source_id', 'native_category'],
                'constraints': [models.UniqueConstraint(fields=('source', 'native_category'), name='unique_prefilter_rule'), models.UniqueConstraint(condition=models.Q(('source__isnull', True)), fields=('native_category',), name='unique_global_prefilter_rule')],
            },
        ),
    ]
