# Generated by Django 5.2.17 on 2026-09-28 07:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_prefilterrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('retry', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'running'), ('success', 'success'), ('partial', 'partial'), ('empty', 'empty'), ('failed', 'failed')], default='running', max_length=16)),
                ('fetched', models.PositiveIntegerField(default=0)),
                ('new', models.PositiveIntegerField(default=0)),
                ('repeated', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crawl_attempts', to='sources.source')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='sources_cra_source__43c3de_idx')],
            },
        ),
    ]
