# Generated by Django 5.2.17 on 2026-09-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_crawlattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_item_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='public_image_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
