# Generated by Django 5.2.17 on 2026-09-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_source_last_item_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='strategy',
            field=models.CharField(choices=[('rss_saba', 'Saba/Nastooh CMS RSS (Mehr, IRNA, ISNA)'), ('rss_generic', 'Standard RSS or Atom feed'), ('listing_detail', 'Listing page -> detail page'), ('listing_relay', 'Listing page -> interstitial -> real article')], max_length=32),
        ),
    ]
