# Generated by Django 5.2.17 on 2026-10-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_alter_source_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='independence_group',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='source',
            name='language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], default='fa', max_length=2),
        ),
        migrations.AddField(
            model_name='source',
            name='license_mode',
            field=models.CharField(choices=[('full', 'Store and show the text'), ('facts_link_out', 'Facts and a link out')], default='full', max_length=16),
        ),
        migrations.AddField(
            model_name='source',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary reporter'), ('aggregator', 'Aggregator')], default='primary', max_length=16),
        ),
    ]
