# Generated by Django 5.2.17 on 2026-10-02 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_source_language_group_license_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlattempt',
            name='error_class',
            field=models.CharField(blank=True, choices=[('network', 'network'), ('blocked', 'blocked'), ('parse', 'parse'), ('rate_limit', 'rate_limit'), ('gone', 'gone'), ('provider', 'provider')], max_length=16),
        ),
        migrations.CreateModel(
            name='CoverageInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('covered', 'covered'), ('gap', 'gap'), ('unknown', 'unknown')], max_length=8)),
                ('error_class', models.CharField(blank=True, choices=[('network', 'network'), ('blocked', 'blocked'), ('parse', 'parse'), ('rate_limit', 'rate_limit'), ('gone', 'gone'), ('provider', 'provider')], max_length=16)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage', to='sources.source')),
            ],
            options={
                'ordering': ['-ended_at', '-id'],
                'indexes': [models.Index(fields=['source', '-ended_at'], name='sources_cov_source__b4d8d6_idx')],
            },
        ),
    ]
