# Generated by Django 5.2.17 on 2026-10-02 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_crawl_error_class_coverage_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('next_at', models.DateTimeField()),
                ('error_class', models.CharField(blank=True, choices=[('network', 'network'), ('blocked', 'blocked'), ('parse', 'parse'), ('rate_limit', 'rate_limit'), ('gone', 'gone'), ('provider', 'provider')], max_length=16)),
                ('gave_up', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fetch_retries', to='sources.source')),
            ],
            options={
                'ordering': ['next_at'],
                'indexes': [models.Index(fields=['gave_up', 'next_at'], name='sources_fet_gave_up_c8cae4_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'url'), name='unique_fetch_retry')],
            },
        ),
    ]
