# Generated by Django 5.1.5 on 2026-09-02 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('gold_18k', 'Gold, 18 carat (گرم طلای ۱۸ عیار)'), ('gold_ounce', 'Gold, global ounce (انس جهانی)'), ('coin_emami', 'Emami coin (سکه امامی)'), ('usd_irr', 'US Dollar / Rial (دلار)'), ('eur_irr', 'Euro / Rial (یورو)')], db_index=True, max_length=32)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['symbol', '-observed_at'], name='market_pric_symbol_6e02f8_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'observed_at'), name='unique_price_observation')],
            },
        ),
        migrations.CreateModel(
            name='PredictionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('gold_18k', 'Gold, 18 carat (گرم طلای ۱۸ عیار)'), ('gold_ounce', 'Gold, global ounce (انس جهانی)'), ('coin_emami', 'Emami coin (سکه امامی)'), ('usd_irr', 'US Dollar / Rial (دلار)'), ('eur_irr', 'Euro / Rial (یورو)')], default='gold_18k', max_length=32)),
                ('window_trading_days', models.PositiveSmallIntegerField(default=1)),
                ('baseline_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('realized_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('realized_pct', models.FloatField()),
                ('direction_correct', models.BooleanField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='inference.evaluation')),
            ],
            options={
                'ordering': ['-computed_at'],
                'constraints': [models.UniqueConstraint(fields=('evaluation', 'symbol', 'window_trading_days'), name='unique_prediction_outcome')],
            },
        ),
    ]
