# Generated by Django 5.2.17 on 2026-10-02 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_storylines'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_key', models.CharField(max_length=64)),
                ('asset_class', models.CharField(blank=True, max_length=32)),
                ('window', models.CharField(max_length=8)),
                ('tier', models.PositiveSmallIntegerField()),
                ('price_before', models.DecimalField(decimal_places=8, max_digits=24)),
                ('price_after', models.DecimalField(decimal_places=8, max_digits=24)),
                ('pct_change', models.FloatField()),
                ('abs_z', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='articles.newsevent')),
            ],
            options={
                'ordering': ['-computed_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'asset_key', 'window'), name='unique_event_reaction')],
            },
        ),
    ]
