# Generated by Django 5.1.5 on 2026-09-02 11:16

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        # Must run before any VectorField is created. Requires the pgvector image (or a
        # superuser); the plain postgres:16 image cannot satisfy this.
        VectorExtension(),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('original_outlet', models.CharField(blank=True, max_length=255)),
                ('original_title', models.TextField()),
                ('lead', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('content_hash', models.CharField(db_index=True, max_length=32)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('published_at_jalali', models.CharField(blank=True, db_index=True, max_length=10)),
                ('published_time', models.CharField(blank=True, max_length=5)),
                ('date_uncertain', models.BooleanField(default=False)),
                ('native_category', models.CharField(blank=True, db_index=True, max_length=64)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('extraction_tier', models.CharField(choices=[('jsonld', 'JSON-LD articleBody'), ('og', 'OpenGraph metadata'), ('css', 'CSS selector'), ('feed', 'Feed entry only'), ('listing', 'Listing row only')], default='css', max_length=16)),
                ('quality_flag', models.CharField(blank=True, db_index=True, max_length=64)),
                ('prefilter_reason', models.CharField(blank=True, db_index=True, max_length=64)),
                ('duplicate_score', models.FloatField(blank=True, null=True)),
                ('duplicate_reason', models.CharField(blank=True, max_length=32)),
                ('fetched_at', models.DateTimeField(db_index=True)),
                ('first_seen_run', models.CharField(blank=True, max_length=32)),
                ('last_seen_run', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='articles.article')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='sources.source')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=64)),
                ('dimensions', models.PositiveSmallIntegerField()),
                ('vector', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('file', models.ImageField(blank=True, upload_to='articles/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='articles/%Y/%m/thumbs/')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('stored', 'Stored'), ('failed', 'Failed'), ('absent', 'No image published')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='articles.article')),
            ],
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source', 'published_at'], name='articles_ar_source__f67b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['duplicate_of'], name='articles_ar_duplica_82d2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['original_outlet'], name='articles_ar_origina_e9f609_idx'),
        ),
        migrations.AddIndex(
            model_name='articleembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='article_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='articleembedding',
            constraint=models.UniqueConstraint(fields=('article', 'model'), name='unique_article_embedding'),
        ),
    ]
