# Generated by Django 5.1.5 on 2026-09-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='source_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
