# Generated by Django 5.2.17 on 2026-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_url_status_and_gone_images'),
        ('sources', '0003_crawlattempt'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='articles_ar_created_b5cc75_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source', 'created_at'], name='articles_ar_source__24b6dc_idx'),
        ),
    ]
