# Generated by Django 5.2.17 on 2026-09-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_articles_ar_created_b5cc75_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('lead', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('content_hash', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=16)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(db_index=True)),
                ('first_seen_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('developing', 'Developing'), ('assessed', 'Assessed'), ('corrected', 'Corrected'), ('withdrawn', 'Withdrawn')], default='developing', max_length=16)),
                ('category', models.CharField(blank=True, db_index=True, max_length=32)),
                ('iran_score', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('global_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assessment_confidence', models.FloatField(blank=True, null=True)),
                ('title_fa', models.TextField(blank=True)),
                ('brief_fa', models.TextField(blank=True)),
                ('brief_en', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, related_name='news_events', to='articles.article')),
                ('primary_article', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='led_event', to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='EventAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=80)),
                ('evidence_hash', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(max_length=32)),
                ('iran_score', models.PositiveSmallIntegerField()),
                ('global_score', models.PositiveSmallIntegerField()),
                ('asset_scores', models.JSONField(default=dict)),
                ('confidence', models.FloatField()),
                ('cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='articles.newsevent')),
            ],
        ),
        migrations.AddIndex(
            model_name='newsevent',
            index=models.Index(fields=['-event_time', '-id'], name='articles_ne_event_t_6603ea_idx'),
        ),
    ]
