# Generated by Django 5.2.17 on 2026-09-29 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_eventreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=2048, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('iran', models.BooleanField(default=True)),
                ('global_events', models.BooleanField(default=False)),
                ('asset_classes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=64)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.newsevent')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.alertsubscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'subscription'), name='one_alert_per_event_subscription')],
            },
        ),
    ]
