# Generated by Django 5.2.17 on 2026-09-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alertsubscription_eventalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='channels_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='channels_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='uncertainty_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='uncertainty_fa',
            field=models.TextField(blank=True),
        ),
    ]
