# Generated by Django 5.2.17 on 2026-09-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_newsevent_channels_en_newsevent_channels_fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
