# Generated by Django 5.2.17 on 2026-09-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_last_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='title_en',
            field=models.TextField(blank=True),
        ),
    ]
