# Generated by Django 5.2.17 on 2026-09-29 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_newsevent_title_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=32)),
                ('title_fa', models.TextField(blank=True)),
                ('title_en', models.TextField(blank=True)),
                ('brief_fa', models.TextField(blank=True)),
                ('brief_en', models.TextField(blank=True)),
                ('channels_fa', models.TextField(blank=True)),
                ('channels_en', models.TextField(blank=True)),
                ('uncertainty_fa', models.TextField(blank=True)),
                ('uncertainty_en', models.TextField(blank=True)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='articles.newsevent')),
            ],
        ),
    ]
