# Generated by Django 5.2.17 on 2026-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_eventrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreview',
            name='skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
