# Generated by Django 5.2.17 on 2026-10-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_eventreview_skipped_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='first_seen_run',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_seen_run',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
