# Generated by Django 5.2.17 on 2026-10-02 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_investor_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('asset', 'Asset'), ('actor', 'Actor'), ('theme', 'Theme')], max_length=8)),
                ('name_fa', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventWatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_links', to='articles.newsevent')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='articles.watchitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'item'), name='one_tag_per_event_item')],
            },
        ),
    ]
