# Generated by Django 5.2.17 on 2026-10-02 11:58

from django.db import migrations, models
from django.db.models import Count


def backfill(apps, schema_editor):
    """Events reported by more than one source are `multi`. Sources have no independence
    groups yet, so each source is its own group, as in core.events.evidence_level."""
    NewsEvent = apps.get_model("articles", "NewsEvent")
    multi = (
        NewsEvent.objects.annotate(groups=Count("articles__source", distinct=True))
        .filter(groups__gt=1)
        .values("id")
    )
    NewsEvent.objects.filter(id__in=multi).update(evidence_level="multi")


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_grouping_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='evidence_level',
            field=models.CharField(choices=[('single', 'One source group'), ('multi', 'Several independent source groups'), ('official', 'Reported by an official source'), ('disputed', 'Sources disagree')], default='single', max_length=16),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
