# Generated by Django 5.2.17 on 2026-10-02 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_newsevent_evidence_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storyline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.TextField(blank=True)),
                ('name_en', models.TextField(blank=True)),
                ('previous_names', models.JSONField(blank=True, default=list)),
                ('last_event_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorylineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storyline_link', to='articles.newsevent')),
                ('storyline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='articles.storyline')),
            ],
        ),
    ]
