# Generated by Django 5.2.17 on 2026-10-02 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_storylines'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stance', models.CharField(choices=[('reports', 'Reports the occurrence'), ('supports', 'Confirms what was reported'), ('contradicts', 'Disputes what was reported'), ('updates', 'Adds a later development')], default='reports', max_length=16)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stances', to='articles.article')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stances', to='articles.newsevent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'article'), name='one_stance_per_member')],
            },
        ),
    ]
