# Generated by Django 5.2.17 on 2026-10-02 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_article_stance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('source_title', models.TextField()),
                ('title', models.TextField()),
                ('model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title_translation', to='articles.article')),
            ],
        ),
    ]
