# Generated by Django 5.2.17 on 2026-10-02 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_title_translation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='hidden_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='hidden_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='TakedownLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('event', 'Event'), ('article', 'Article')], max_length=8)),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('action', models.CharField(choices=[('hide', 'Hide'), ('unhide', 'Unhide')], max_length=8)),
                ('reason', models.CharField(max_length=255)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
