# Generated by Django 5.1.5 on 2026-09-02 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('inference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_as_left', models.CharField(choices=[('a', 'Variant A'), ('b', 'Variant B')], default='a', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_pairs', to='articles.article')),
                ('variant_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_a', to='inference.promptvariant')),
                ('variant_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_b', to='inference.promptvariant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ABFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('tie', 'Tie')], max_length=8)),
                ('reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_feedback', to=settings.AUTH_USER_MODEL)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='review.abpair')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stratum', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('reviewed_category', models.CharField(blank=True, choices=[('security', 'Security'), ('economics', 'Economics'), ('security/economics', 'Security/Economics'), ('other', 'Other')], max_length=32)),
                ('confidence_occurrence', models.CharField(blank=True, choices=[('خیلی کم', 'Very low (خیلی کم)'), ('کم', 'Low (کم)'), ('متوسط', 'Medium (متوسط)'), ('زیاد', 'High (زیاد)'), ('خیلی زیاد', 'Very high (خیلی زیاد)')], max_length=16, null=True)),
                ('gold_price_impact', models.CharField(blank=True, choices=[('خیلی کم', 'Very low (خیلی کم)'), ('کم', 'Low (کم)'), ('متوسط', 'Medium (متوسط)'), ('زیاد', 'High (زیاد)'), ('خیلی زیاد', 'Very high (خیلی زیاد)')], max_length=16, null=True)),
                ('security_relevance', models.CharField(blank=True, choices=[('خیلی کم', 'Very low (خیلی کم)'), ('کم', 'Low (کم)'), ('متوسط', 'Medium (متوسط)'), ('زیاد', 'High (زیاد)'), ('خیلی زیاد', 'Very high (خیلی زیاد)')], max_length=16, null=True)),
                ('gold_trend', models.CharField(blank=True, choices=[('↑', '↑ Up'), ('↓', '↓ Down'), ('خنثی', 'Neutral (خنثی)'), ('نامطمئن', 'Uncertain (نامطمئن)')], max_length=16, null=True)),
                ('one_line', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_case', to='articles.article')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='abpair',
            constraint=models.UniqueConstraint(fields=('article', 'variant_a', 'variant_b'), name='unique_ab_pair'),
        ),
        migrations.AddConstraint(
            model_name='abpair',
            constraint=models.CheckConstraint(condition=models.Q(('variant_a', models.F('variant_b')), _negated=True), name='ab_pair_variants_differ'),
        ),
        migrations.AddConstraint(
            model_name='abfeedback',
            constraint=models.UniqueConstraint(fields=('pair', 'user'), name='unique_ab_feedback_per_user'),
        ),
        migrations.AddIndex(
            model_name='reviewcase',
            index=models.Index(fields=['status', 'stratum'], name='review_revi_status_2a38d5_idx'),
        ),
    ]
